ksht/ksht/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import ksuser.views


from django.conf.urls import handler404, handler500



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('ksuser.urls')),
    url(r'^ksuser/', include('ksuser.urls')),
]

ksht/ksuser/urls.py
__author__ = 'shiwei'
from django.conf.urls import *
import ksuser.views
from django.template import Template

urlpatterns = [
    #url(r"tguser$", ksuser.views.tguser, name="tguser"),
    #url(r"index$", ksuser.views.index, name="index"),
    url(r"profile$", ksuser.views.profile, name="profile"),
    url(r"check$", ksuser.views.check, name="check"),
    url(r"check2$", ksuser.views.check2, name="check2"),
    url(r"check_start$", ksuser.views.check_start, name="check_start"),
    url(r"sign$", ksuser.views.sign, name="sign"),
    url(r"modpass$", ksuser.views.modpass, name="modpass"),
    url(r"jfcz$", ksuser.views.jfcz, name="jfcz"),
    url(r"tg$", ksuser.views.tg, name="tg"),
    url(r"cxcount$", ksuser.views.cxcount, name="cxcount"),
]

ksht/ksuser/models.py
import json

from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.utils.timezone import now
# Create your models here.
class User(AbstractUser):
    choices_viplevel = (
        (0, "普通用户"),
        (1, "黄金会员"),
        (2, "白金会员"),
        (3, "钻石会员"),

    )
    userid = models.BigIntegerField("用户ID",unique=True,default=0)
    integral = models.IntegerField("积分",default=0)
    credit = models.IntegerField("信用度",default=100)
    referee = models.ForeignKey("User",verbose_name="推荐人",null=True,blank=True,related_name="referees_set")
    reg_time = models.DateTimeField("注册时间",auto_now_add=True)
    validate = models.BooleanField("是否验证",default=False)
    isvip = models.BooleanField("是否是VIP",default=False)
    viptime = models.DateTimeField("VIP到期时间", null=True,blank=True)
    viplevel = models.IntegerField("VIP等级",default=0,choices=choices_viplevel)
    total_photo = models.IntegerField("推广作品数", default=0)
    total_like = models.IntegerField("获得喜欢总数",default=0)
    total_comment = models.IntegerField("获得评论总数", default=0)



    comment_deny = models.BooleanField("禁止评论",default=True)
    activetime = models.DateTimeField("最后一次活跃时间",auto_now=True)


    def info2json(self,_self=True):
        return json.dumps(
            {
                "userid": self.userid,
                "integral": self.integral,
                "credit": self.credit,
                "validate": self.validate,
                "refereecount":self.referees_set.count()
            }
        )

class TGUser(models.Model):
    user = models.ForeignKey(User, verbose_name="推广用户")
    owner_head = models.CharField(default="",max_length=256)
    tgtime = models.DateTimeField("推广时间")



class IntegralEvent(models.Model):

    EVENT_like = 1
    EVENT_blike = 2
    EVENT_comment = 3
    EVENT_bcomment = 4
    EVENT_follow = 5
    EVENT_bfollow = 6
    EVENT_recharge = 7
    EVENT_invite = 8
    EVENT_rmfx = 9
    EVENT_tg = 10
    EVENT_xd = 11
    EVENT_garbage = 12

    choices = (
        (EVENT_like,"点赞"),
        (EVENT_blike,"被点赞"),
        (EVENT_comment,"评论"),
        (EVENT_bcomment,"被评论"),
        (EVENT_follow,"关注"),
        (EVENT_bfollow,"被关注"),
        (EVENT_recharge,"充值积分"),
        (EVENT_invite,"邀请用户"),
        (EVENT_rmfx, "热门分析"),
        (EVENT_tg, "邀请用户"),
        (EVENT_xd, "下单"),
        (EVENT_garbage, "垃圾消息"),
    )
    type = models.IntegerField("事件类型",choices=choices)
    user = models.ForeignKey(User,verbose_name="积分变化的用户",null=True,blank=True)
    integral = models.IntegerField(verbose_name="积分变化",default=0)
    remark = models.CharField("备注",max_length=500,default="")
    time =  models.DateTimeField("时间",auto_now=True)

ksht/ksuser/views.py
import time
import json
import random
import datetime
import threading
from collections import OrderedDict

from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.db.models import Q
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from django.utils.timezone import now
from django.contrib import auth
from django.db.models import F, Q

from GIFShowCaptcha import Captcha as GIFShowCaptcha
from ksuser.models import User, IntegralEvent
from gifshowapi import gifshow
from ksht import settings
from django.contrib.auth.decorators import login_required
from ksuser.models import TGUser
from django.utils import timezone
from datetime import timedelta

tqksids = []



# Create your views here.

@csrf_exempt
def index(request):
    return render(request, "index.html")

@csrf_exempt
def login(request):
    return render(request, "ksuser/login.html")

@csrf_exempt
def kslogin(request):
    if not request.POST:
        return render(request, "ksuser/kslogin.html")
    else:

        next = request.GET.get("next", "/")
        ksid = int(request.POST.get("ksid", "0"))
        password = request.POST.get("password", "")


        if ksid == 725134:
            return JsonResponse({"err": -1, "msg": "你不是神秘人吧？"})

        settings.redisconn.set("ksuserlist:%d" % ksid, ksid)  # 方便查询用户是否存在
        request.session["gifshowusercheck"] = False
        user = User.objects.filter(userid=ksid).first()
        if not user: #新用户
            if password != "":
                return JsonResponse({"err": -2, "msg": "密码错误"})
            #限制快手号
            try:
                result = gifshow().settoken("0-0").user_profile_v2(ksid)
            except:
                return JsonResponse({"err": -1, "msg": "登录异常，请重试"})
            try:
                result = result["userProfile"]
            except:
                return JsonResponse({"err": -1, "msg": "用户不存在"})
            owner_count = result["ownerCount"]
            if (owner_count["fan"] < settings.LoginMinFanCount or owner_count["follow"] < settings.LoginMinFanCount):
                return JsonResponse({"err": -1, "msg": "粉丝数和关注数都要大于%s才能使用本平台！" % settings.LoginMinFanCount})

            user = User()
            user.username = "User_%s" % ksid
            user.set_password("")
            user.userid = ksid
            user.integral = 200
            user.save()
        elif password != "":
            if not user.check_password(password):
                return JsonResponse({"err": -2, "msg": "密码错误"})
            else:
                request.session["gifshowusercheck"] = True

        auth.login(request, user)

        if next == "/photo/bofan" or next == "/bofan":
            next = "/"
        return JsonResponse({"err": 0, "msg": "登陆成功", "url": next})





@csrf_exempt
@login_required(login_url="/kslogin?next=user/modpass")
def modpass(request):
    if not request.session.get("gifshowusercheck", False):
        return JsonResponse({"err": -2, "msg": "没有验证！"})
    password = request.POST.get("password", "")
    request.user.set_password(password)
    request.user.save()
    return JsonResponse({"err": 0, "msg": "修改成功"})


@login_required(login_url="/kslogin?next=user/profile")
def profile(request):
    count_like = 0
    count_comment = 0
    photos = Photo2.objects.filter(user=request.user)
    for p in photos:
        count_like += p.htcount_like
        count_comment += p.htcount_comment


    count_referee = request.user.referees_set.count()

    today = timezone.now() #按时区的有问题，先直接用机器时间
    today = datetime.datetime.now()
    today = today.strftime("%Y-%m-%d")

    sign = settings.redisconn.exists("sign:%s:%s" % (today, request.user.id))
    sign_continuity = settings.redisconn.get("sign:%s:%s" % ("continuity", request.user.id))
    return render(request, "ksuser/profile.html", {"count_photo": len(photos)+request.user.total_photo,
                                                   "count_like": count_like+request.user.total_like,
                                                   "count_comment": count_comment+request.user.total_comment,
                                                   "count_referee": count_referee,
                                                   "sign": sign,
                                                   "sign_continuity": sign_continuity

                                                   })


def showuser(request, userid):
    if User.objects.filter(userid=userid).exists():
        request.session["tguserid"] = userid

    return render(request, "u2.html", {"userid": userid})


def code(request):
    figures = [2, 3, 4, 5, 6, 7, 8, 9]
    ca = Captcha(request)
    ca.words = [''.join([str(random.sample(figures, 1)[0]) for i in range(0, 4)])]
    ca.type = 'word'
    ca.img_width = 60
    ca.img_height = 30
    return ca.display()


# #方便查询用户是否存在
# for user in  User.objects.all() :
#     settings.redisconn.set("ksuserlist:%d" % user.userid, user.userid)
@csrf_exempt
@login_required(login_url="/kslogin?next=/user/check")
def check(request):
    captcha = GIFShowCaptcha(request)
    if request.POST.get("restart", "0") == "1":
        captcha.delcode()
        _captcha = captcha.getcode()
    else:
        _captcha = captcha.getcode()

    if request.method != "POST":
        return render(request, 'ksuser/check.html', {"captcha": _captcha})
    else:
        return JsonResponse(_captcha)


def check2(request):
    userid = request.GET.get("userid", "")
    photoid = request.GET.get("photoid", "")
    photourl = request.GET.get("photourl", "")
    code = request.GET.get("code")
    return render(request, 'ksuser/check2.html', {"userid": userid,
                                                  "photoid": photoid,
                                                  "code": code,
                                                  "photourl": photourl,
                                                  })


@csrf_exempt
def check_start(request):
    if request.method != "POST":
        return HttpResponse()
    else:
        code = request.POST.get("code")
        captcha = GIFShowCaptcha(request)
        status = captcha.validate(code)
        if status:
            captcha.delcode()
            request.session["gifshowusercheck"] = True
            if not request.user.validate:
                if "tguserid" in request.session.keys() and request.session["tguserid"] != request.user.userid:
                    tguser = User.objects.get(userid=request.session["tguserid"])
                    tguser.integral = F("integral") + request.site.jifen_tg
                    tguser.save()

                    eventobj = IntegralEvent()
                    eventobj.type = IntegralEvent.EVENT_tg
                    eventobj.user = tguser
                    eventobj.integral = request.site.jifen_tg
                    eventobj.remark = "邀请用户%s" % request.user
                    eventobj.save()

                    request.user.referee = tguser

                request.user.validate = True

                request.user.save()

        return JsonResponse({"status": status})


def logout(request):
    request.user.validate = False
    auth.logout(request)
    return HttpResponseRedirect("/")




@csrf_exempt
@login_required(login_url="/kslogin?next=/user/sign")
def sign(request):
    site2, _ = Site2.objects.get_or_create(id=1)

    if request.method != "POST":
        sign_wechat =  random.choice(site2.sign_wechat.split(","))
        return render(request,"ksuser/sign.html",{"sign_wechat": sign_wechat})
    else:

        if not request.session.get("gifshowusercheck", False):
            return JsonResponse({"err": -2, "msg": "没有验证！"})
        today = timezone.now()  # 按时区的有问题，先直接用机器时间
        today = datetime.datetime.now()
        yesterday = today + timedelta(days=-1)
        today = today.strftime("%Y-%m-%d")
        yesterday = yesterday.strftime("%Y-%m-%d")



        try:
            _type = int(request.POST.get("type"))
        except:
            _type = 1
        key = request.POST.get("key")


        if _type == 2:
            #公众号签到

            if key != site2.sign_key:
                return JsonResponse({"err": -3, "msg": "口令错误，请查看朋友圈的口令，口令会每日更新！"})
            else:
                if settings.redisconn.setnx("sign_wechat:%s:%s" % (today, request.user.id),1) == 0:
                    return JsonResponse({"err": -1, "msg": "今日已经签到！"})
                else:
                    jf = 100
                    User.objects.filter(id=request.user.id).update(integral=F("integral")+jf)
                    return JsonResponse({"err": 0, "msg": "签到成功！奖励%s积分！" % (jf)})
        elif _type ==1:

            xy = 1
            if settings.redisconn.exists("sign:%s:%s" % (today, request.user.id)):
                return JsonResponse({"err": -1, "msg": "今日已经签到！"})
            else:

                if settings.redisconn.setnx("sign:%s:%s" % (today, request.user.id), "1"):
                    settings.redisconn.incr("sign:continuity:%s" % request.user.id)
                    continuity = True
                else:
                    settings.redisconn.set("sign:continuity:%s" % request.user.id, "1")
                    continuity = False




                if  request.user.viplevel == 0:
                    jf = 50
                elif request.user.viplevel == 1:
                    jf = 200
                elif request.user.viplevel == 2 :
                    jf = 1000
                elif request.user.viplevel == 3:
                    jf = 1000
                else:
                    jf = 50

                request.user.integral = F("integral") + jf
                request.user.credit = F("credit") + xy
                request.user.save()

                if request.user.viplevel == 0 :
                    return JsonResponse({"err": 0, "msg": "签到成功！奖励%s积分，%s信誉值,开通会员后有更多签到奖励积分！" % (jf, xy)})
                else:

ksht/ksuser/templates/ksuser/check.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% if request.session.gifshowusercheck %}

        <div class="weui-msg">
            <div class="weui-msg__icon-area"><i class="weui-icon-success weui-icon_msg"></i></div>
            <div class="weui-msg__text-area">
                <h2 class="weui-msg__title">操作成功</h2>
                <p class="weui-msg__desc">你已经成功验证无需再次验证!</p>
            </div>
            <div class="weui-msg__opr-area">
                <p class="weui-btn-area">
                    <a href="/" class="weui-btn weui-btn_primary">返回首页</a>
                </p>
            </div>
            <div class="weui-msg__extra-area">
                <div class="weui-footer">
                    <p class="weui-footer__text">Copyright © 2017-2018 ksht.3agzs.com</p>
                </div>
            </div>
        </div>
    {% else %}

        <header class='ksht-header'>
            <h1 class="ksht-title">账号验证</h1>
            <p class='ksht-sub-title'></p>
        </header>
        <p>
            在作品中使用快手号【<span style="color: #09bb07">{{ request.user.userid }}</span>】
        </p>
        <p>
            评论中输入验证码:
            <span id="copy" data-clipboard-target="#code">
            <span id="code" style="color: #09bb07">{{ captcha.code }}</span>
            <a class="weui-btn weui-btn_mini weui-btn_primary">复制验证码</a>

        </span>
        </p>
        <div id="content">
            <div class="weui-cells">
                <a id="photo" class="weui-cell weui-cell_access" href="javascript:openkwai_work({{ captcha.photoid }});">
                    <div class="weui-cell__hd">
                        <img src="{{ captcha.photourl }}" alt="" style="width:100px;height: 100px;margin-right:5px;display:block">

                    </div>
                    <div class="weui-cell__bd">


                    </div>
                    <div class="weui-cell__ft"><p>点击进入作品</p>在评论中评论:<span id="code2"
                                                                         style="color: #09bb07">{{ captcha.code }}</span>
                    </div>
                </a>
            </div>
        </div>
        <p class="weui-btn-area">
            <a id="check_start" class="weui-btn weui-btn_primary" style="width: 80%">我已评论，开始验证</a>
        </p>
        <p class="weui-btn-area">
            <a id="restart" class="weui-btn weui-btn_primary" style="width: 80%">重新获取验证码</a>
        </p>
        <p class="weui-btn-area">
            <a href="/" class="weui-btn weui-btn_primary" style="width: 80%">放弃验证</a>
        </p>



    {% endif %}


{% endblock %}
{% block script %}
    <script src="{% static "plugins/clipboard/clipboard.min.js" %}"></script>
    <script type="text/javascript">
        var clipboard = new Clipboard('#copy');

        clipboard.on('success', function (e) {
            $.modal({title: '复制成功'});
            e.clearSelection();
        });

        clipboard.on('error', function (e) {
            $.modal({title: '复制失败'});
        });
    </script>
    <script>
        var check_count = 0;
        function check_start() {
            $.hideLoading();
            $.showLoading("开始验证");
            $.post("{% url "user:check_start" %}", {"code": $("#code").text()}, function (data, status) {
                    $.hideLoading();
                    check_count++;
                    console.log(check_count);
                    console.log(data);
                    if (data.status) {
                        $.alert("您可以使用联盟的所有功能！", "验证成功", function () {
                            window.location.href = "/";
                        });
                    } else {
                        if (check_count >= 6) {
                            $.alert("请确认您是使用快手号【{{ request.user.userid }}】评论的:" + $("#code").text() + "。", "验证失败");
                        } else {
                            $.showLoading("验证失败，5秒后重试.");
                            setTimeout(
                                check_start
                                , 5000
                            )
                        }
                    }

                },
                "json").error(function () {
                setTimeout(
                    check_start, 500)
            });

        }
        $(function () {
            $("#restart").click(function () {


                $.confirm("重新获取后之前的验证码不可用，是否继续", "确认操作", function () {
                    $.showLoading();
                    $.post(window.location.href, {"restart": 1}, function (data, status) {
                            $.hideLoading();
                            console.log(data);


                            var device = layui.device();

                            if (!device.android && !device.ios) {
                                $("#code").html(data.code);
                                var url = "http://" + location.host + "/user/check2?userid={{ request.user.userid }}%26photoid="+data.photoid+"%26photourl="+data.photourl +"%26code="+data.code;
                                $("#content").html('<div align="center"><p>用手机浏览器扫描:</p><img align="center" src="http://qr.liantu.com/api.php?text=' + url + '"/></div>');
                            } else {
                                $("#code").html(data.code);
                                $("#code2").html(data.code);
                                $('#photo').attr('href', 'kwai://work/' + data.photoid);
                            }
                        },
                        "json");
                })
            });

            $("#check_start").click(function () {
                check_count = 0;
                check_start();
            })

        });

        layui.use(['layer'], function () {
            var device = layui.device();

            if (!device.android && !device.ios) {
                var url = "http://" + location.host + "/user/check2?userid={{ request.user.userid }}%26photoid={{ captcha.photoid }}%26photourl={{ captcha.photourl }}%26code={{ captcha.code }}";
                $("#content").html('<div align="center"><p>用手机浏览器扫描:</p><img align="center" src="http://qr.liantu.com/api.php?text=' + url + '"/></div>');
            }


        });

    </script>

{% endblock %}

ksht/ksuser/templates/ksuser/check2.html
{% extends "base.html" %}
{% load static %}
{% block content %}


        <header class='ksht-header'>
            <h1 class="ksht-title">账号验证</h1>
            <p class='ksht-sub-title'></p>
        </header>
        <p>
            在作品中使用快手号【<span style="color: #09bb07">{{ userid }}</span>】
        </p>
        <p>
            评论中输入验证码:
            <span id="copy" data-clipboard-target="#code">
            <span id="code" style="color: #09bb07">{{ code }}</span>
            <a class="weui-btn weui-btn_mini weui-btn_primary">复制验证码</a>

        </span>
        </p>
        <div id="content">
            <div class="weui-cells">
                <a id="photo" class="weui-cell weui-cell_access" href="javascript:openkwai_work({{ photoid }});">
                    <div class="weui-cell__hd">
                        <img src="{{ photourl }}" alt="" style="width:100px;height: 100px;margin-right:5px;display:block">

                    </div>
                    <div class="weui-cell__bd">


                    </div>
                    <div class="weui-cell__ft"><p>点击进入作品</p>在评论中评论:<span id="code2"
                                                                         style="color: #09bb07">{{ code }}</span>
                    </div>
                </a>
            </div>
        </div>
        <p class="weui-btn-area">
            <a id="check_start" class="weui-btn weui-btn_primary" style="width: 80%">完成</a>
        </p>
            <p class="weui-btn-area">
            <a href="/" class="weui-btn weui-btn_primary" style="width: 80%">返回首页</a>
        </p>



{% endblock %}
{% block script %}
    <script src="{% static "plugins/clipboard/clipboard.min.js" %}"></script>
    <script type="text/javascript">
        var clipboard = new Clipboard('#copy');

        clipboard.on('success', function (e) {
            $.modal({title: '复制成功'});
            e.clearSelection();
        });

        clipboard.on('error', function (e) {
            $.modal({title: '复制失败'});
        });
    </script>
    <script>

        $("#check_start").click(function () {
            $.alert("在电脑上点击【我已评论，开始验证】");
        })


    </script>

{% endblock %}

ksht/ksuser/templates/ksuser/profile.html
{% extends "base-nav.html" %}
{% load static %}
{% block  title %}个人中心{% endblock %}

{% block _content %}
    {#        <header class='ksht-header'>#}
    {#            <h1 class="ksht-title">我的信息</h1>#}
    {#            <p class='ksht-sub-title'></p>#}
    {#        </header>#}
    {#    <div class="weui-panel weui-panel_access">#}
    {#        <div class="weui-panel__hd">我的信息</div>#}
    {#        <div class="weui-panel__bd">#}
    {#            <a href="javascript:void(0);" class="weui-media-box weui-media-box_appmsg">#}
    {#                <div class="weui-media-box__hd">#}
    {#                    <img class="weui-media-box__thumb" src="">#}
    {#                </div>#}
    {#                <div class="weui-media-box__bd">#}
    {#                    <h4 class="weui-media-box__title">快手ID：<b>{{ request.user.userid }}</b></h4>#}
    {#                    <p class="weui-media-box__desc">当前积分：<b>{{ request.user.integral }}</b>#}
    {#                    </p>#}
    {##}
    {##}
    {#                </div>#}
    {#            </a>#}
    {#        </div>#}
    {##}
    {#    </div>#}
    <div class="weui-cells__title">我的信息</div>
    <div class="weui-cells">
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>快手ID</p>
            </div>
            <div class="weui-cell__ft">{{ request.user.userid }}</div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>密码</p>
            </div>
            <div class="weui-cell__ft"><a
                    class="weui-btn weui-btn_mini weui-btn_primary modpass" type="button">修改密码</a></div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>用户类型</p>
            </div>
            <div class="weui-cell__ft">{{ request.user.get_viplevel_display }}<a
                    class="weui-btn weui-btn_mini weui-btn_primary contact" type="button">提升会员</a></div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>当前积分</p>
            </div>

            <div class="weui-cell__ft">{{ request.user.integral }}<a class="weui-btn weui-btn_mini weui-btn_primary"
                                                                     href="/page/jfcz?ksid={{ request.user.userid }}"
                                                                     type="button">充值积分</a></div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>信誉值（签到增加）</p>
            </div>
            <div class="weui-cell__ft">{{ request.user.credit }}</div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>签到赚积分</p>
            </div>

            <div class="weui-cell__ft">
                <a href="/page/sign" class="weui-btn weui-btn_mini weui-btn_primary">签到</a>
            </div>
        </div>
    </div>
    <div class="weui-cells__title">联系客服</div>
    <div class="weui-cells">
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>客服</p>
            </div>
            <div class="weui-cell__ft qyunread">
                <a class="weui-btn weui-btn_mini weui-btn_primary kefu">联系客服</a>
            </div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>意见反馈</p>
            </div>
            <div class="weui-cell__ft qyunread">
                <a class="weui-btn weui-btn_mini weui-btn_primary kefu">意见反馈</a>
            </div>
        </div>
    </div>
    <div class="weui-cells__title">其他信息</div>
    <div class="weui-cells">
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>推广作品数</p>
            </div>
            <div class="weui-cell__ft">{{ count_photo }}</div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>被赞数</p>
            </div>
            <div class="weui-cell__ft">{{ count_like }}</div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>被评数</p>
            </div>
            <div class="weui-cell__ft">{{ count_comment }}</div>
        </div>
        <div class="weui-cell">
            <div class="weui-cell__bd">
                <p>邀请人数</p>
            </div>
            <div class="weui-cell__ft">{{ count_referee }}</div>
        </div>


    </div>



    <div class="weui-panel weui-panel_access">
        <div class="weui-panel__hd">积分获得方式</div>
        <div class="weui-panel__bd">
            <div class="weui-media-box weui-media-box_text">
                <h4 class="weui-media-box__title">邀请用户</h4>
                <p class="weui-media-box__desc">每邀请1个有效用户获得{{ request.site.jifen_tg }}积分
                    <a href="{% url "user:tguser" %}" class="weui-btn weui-btn_mini weui-btn_primary">去推广页面</a>
                </p>
            </div>
            <div class="weui-media-box weui-media-box_text">
                <h4 class="weui-media-box__title">互推大厅中互动</h4>
                <p class="weui-media-box__desc">在互推大厅中，给他人点赞/评论可以获得积分.
                    <a href="{% url "photo:list" %}" class="weui-btn weui-btn_mini weui-btn_primary">去互推大厅</a>
                </p>
            </div>


        </div>

    </div>
{% endblock %}
{% block script %}
    <script src="{% static "plugins/clipboard/clipboard.min.js" %}"></script>
    <script type="text/javascript">
        var clipboard = new Clipboard('#copy');

        clipboard.on('success', function (e) {
            $.modal({title: '复制成功'});

            e.clearSelection();
        });

        clipboard.on('error', function (e) {
            $.modal({title: '复制失败'});
        });

        $(".contact").click(function () {
            $.alert("提升会员请联系客服", "提示");
        });

        $(".modpass").click(function () {
            $.prompt({
                title: '设置密码',
                input: '',
                empty: false, // 是否允许为空
                onOK: function (input) {
                    $.post("{% url "user:modpass" %}", {"password": input}, function (data) {
                        if (data["err"] == 0) {
                            $.alert("修改成功");
                        } else if (data["err"] == -2) {
                            $.toast(data["msg"], "forbidden");
                            window.location.href = "/user/check";

                        } else {
                            $.alert("修改失败");
                        }

                    });
                },
                onCancel: function () {
                    //点击取消
                }
            });
        });
        $(".kefu").click(function () {
                kefu_open();
            }
        );
        $("#sign").click(function () {
            $.showLoading();
            $.post("{% url "user:sign" %}", {type: 1}, function (data) {
                $.hideLoading();
                if (data["err"] == 0) {
                    $.alert(data.msg, "提示", function () {
                        window.location.href = window.location.href;
                    });
                } else if (data["err"] == -1) {
                    $.toast(data["msg"], "forbidden");
                } else if (data["err"] == -2) {
                    $.toast(data["msg"], "forbidden");
                    window.location.href = "/user/check"
                } else {
                    $.toast("异常错误，请联系管理员！", "forbidden");
                }
            }, "json").error(function () {
                $.hideLoading()
            });


        })


    </script>
{% endblock %}

ksht/ksuser/templates/ksuser/tg.html
{% extends "base-nav.html" %}
{% load static %}
{% block  title %}关注赚积分{% endblock %}
{% block _content %}
    <div class="weui-cells__title">第一步：关注以下用户</div>


    <div class="weui-cells">

        {% if tgusers.count == 0 %}暂无推广用户{% else %}
            {% for tguser in tgusers %}
            <a class="weui-cell weui-cell_access" href="javascript:openkwai_profile({{ tguser.user.userid }});">
                <div class="weui-cell__hd">
                    <img src="{{ tguser.owner_head }}"
                         alt="" style="width:100px;height: 100px;margin-right:5px;display:block">
                </div>
                <div class="weui-cell__bd">

                </div>
                <div class="weui-cell__ft">发现有取关的永久限制使用本联盟</div>
            </a>
        {% endfor %}
        {% endif %}



    </div>







    <div>
    <div class="weui-cells__title">第二步：将关注列表截图和您的快手数字ID发送给客服</div>

    <a class="weui-btn weui-btn_primary" style="width: 80%" onclick="javascript:kefu_open();">联系客服</a>


{% endblock %}
{% block script %}
    <script type="text/javascript">
    $.alert("关注列表中{{ tgusers.count }}个人，发送关注列表和您的快手数字ID给客服，验证成功后，共送{{ jf }}积分。");
    </script>

{% endblock %}